### ISSUE TITLE
v2009.06 with ARC support?

### ISSUE THREAD

**Issue by rofrankel** [foss-for-synopsys-dwc-arc-processors/u-boot#3]
Hi, was there ever a fork of v2009.06 with ARC support?  I don't see such a tag in the repo, but I have reason to believe it may have existed:  I have a vendor fork of u-boot 2009.06 which includes the vendor's changes in addition to ARC support, and I would like to separate the ARC changes from the vendor changes.

**Comment by abrodkin** [comment]
Hi Richard,

There were no official U-Boot port for ARC until v2014.03.
Still we did have something internal based on version v2009.06. But I'm not aware of wide availability of that version with ARC support. That said sources that you have access to most probably matches those we have internally and so there's no real point in trying to distill vendor's changes from "vanilla" ARC U-Boot v2009.06 which didn't exist at that time.

Moreover I would propose you to switch to modern U-Boot instead of that old thing you were referring to. Because up to date U-Boot port for ARC (we have all our changes upstream and this GitHub repo is mostly a legacy that we plan to leave at some point in the future while continue to do all development in upstream repo http://git.denx.de/?p=u-boot/u-boot-arc.git) is significantly cleaner and uses as little architecture-specific code as possible relying on generic code for most of things. That makes addition of new platforms/boards as simple as creation of config files.

So if you consider to try recent U-Boot on your platform just let me know and I'll try to help you with that.

-Alexey

**Comment by rofrankel** [comment]
Thanks Alexey!  I think we are mostly on the same page, in that my goal is to use a newer version of U-Boot.  The reason having the ARC version of v2009.06 would be helpful is that it would let me separate out the vendor changes from the ARC changes, and then apply those to a newer U-Boot.

I am quite sure there are vendor-specific changes beyond ARC support, because, for example, they added an option to mkimage called xyz_flags (imagine that the vendor is named XYZ).  But it's a little tricky to figure out exactly what they touched and what they didn't.  Some of the changes they made are in what was then lib_arc/arclinux.c, but without the v2009.06 version of arclinux.c it is hard to be sure I am isolating their changes and not porting forward any stale code (or even worse, bugs that have since been fixed).

If you could make the v2009.06 version of U-Boot + ARC available, either here or at git.denx.de, it would be a huge help.  Other suggestions for how to isolate their changes are also welcome; my request just seemed like the simplest way to do it.

**Comment by abrodkin** [comment]
Hi Richard,

Looks like we have things you might be interested already publicly available.
Please check this link http://sourceforge.net/projects/arc-linux/files/U-Boot/

Let me know if it helps and if you need any assistance in your work on moving to most recent U-Boot.

-Alexey

**Comment by rofrankel** [comment]
Thanks!  That looks like exactly what I needed. :)
